name: GitHub指标

on:
  # 每天自动运行
  schedule: [{ cron: "0 0 * * *" }]
  # 允许手动触发
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub令牌
          token: ${{ secrets.METRICS_TOKEN }}
          # 输出文件名
          filename: github-metrics.svg
          # 启用的指标
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_stargazers: yes
