name: 3D贡献图

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 生成3D贡献图
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: zyh3699
          SETTING_JSON: profile-3d-contrib/settings.json
        with:
          # 生成多种样式
          opt_out: ""
      - name: 提交并推送
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "更新3D贡献图" || exit 0
          git push
